### ISSUE TITLE
Client can't be fired and i dont know why

### ISSUE THREAD

**Issue by abidbmt** [ffrostflame/BridgeNet2#34]
I made a testing place which fires the Remote on the Server, which the client connects to and then answers but when i tested it, i found out that the Client never gets fired for no apparent reason. Here is the place with the code for you to test out

https://www.mediafire.com/file/vtk0tn1tbt9x268/Broken.rbxl/file

**Comment by abidbmt** [comment]
Oh yeah here is the console output:
![Screenshot 2023-08-07 112236](https://github.com/ffrostflame/BridgeNet2/assets/62698817/3ccfbf2d-a275-46bf-8835-2f1aed9d6012)

**Comment by abidbmt** [comment]
hello? @ffrostflame

**Comment by ffrostfall** [comment]
Sorry for the long wait, I need to check github more often tbh. This should be fixed with the latest update
