### ISSUE TITLE
loadingPlayersQueue not merged properly

### ISSUE THREAD

**Issue by TRHeliad** [ffrostflame/BridgeNet2#35]
The line
```Lua
TableKit.MergeArrays(loadingPlayersQueue[player][identifier], content)
```
in `ServerProcess` I think was meant to be
```Lua
loadingPlayersQueue[player][identifier] = TableKit.MergeArrays(loadingPlayersQueue[player][identifier], content)
```
since the TableKit method creates and returns a new table for the merge instead of modifying the passed table.

Maybe you could also try using table.move to put content into the queue instead of using MergeArrays so that you don't create a new table unnecessarily.

**Comment by ffrostfall** [comment]
Yeah, this seems right. will fix

**Comment by ffrostfall** [comment]
Fixed
