### ISSUE TITLE
Close invocations return first request's result

### ISSUE THREAD

**Issue by TRHeliad** [ffrostflame/BridgeNet2#40]
This could be fixed since I am running an old version, but I think it might not be.

Basically if you run *multiple Invocations* on the same bridge *before* earlier ones were able to complete, the result of the first one to return will be sent to all the invocations which are queued up.

For me I just kept an invocation count and sent the number with the request so it could be identified. Probably not the best solution, but it works well enough.

**Comment by ffrostfall** [comment]
Fixed in the next update
